# Site settings
title: Civic Workbench
email: jonathan@eylerwerve.com
description: > # this means to ignore newlines until "baseurl:"
  Open source tools for community management.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://civicworkbench.com" # the base hostname & protocol for your site
twitter_username: civicworkbench
github_username:  jonathan-eyler-werve

# Build settings
markdown: kramdown
